Question 1. a to d

In [1]:
import numpy as np

In [2]:
print(np.version.version)

1.26.4


In [3]:
print(np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: 

In [4]:
null_vec_1 = np.zeros(10)

print(null_vec_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
null_vec_2 = np.zeros(10)

null_vec_2[4] = 1
print(null_vec_2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
vec_1 = np.random.randint(100, size=(10,))
vec_1

array([41, 67, 45, 14, 79, 48, 88, 22, 79,  8])

In [7]:
vec_2 = np.flip(vec_1)
print(vec_2)

[ 8 79 22 88 48 79 14 45 67 41]


In [8]:
for i in range(0,2):
    print(i)

0
1


Question 1.e)

In [9]:
l1 = []
n = 30*30
counter = 0
# l1.append(2)
# l1

for i in range(n):
    l1.append(counter)
    counter = (counter + 1) % 2
print(l1)

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 

In [10]:
root_n = int(np.sqrt(n))
checker_vector = np.array(l1).reshape(root_n, root_n)
print(checker_vector)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0

Question 1,f)

In [11]:
root_n = 10
random_matrix = np.random.randint(1000, size=(root_n, root_n))
m = np.random.randint(root_n)

def mth_element(a_row_of_random_matrix):
    return a_row_of_random_matrix[m]

# np.sort(random_matrix, axis=1)

In [12]:
random_matrix

array([[466, 847, 320, 602, 608, 490,  78, 363, 154, 778],
       [ 94, 371, 113, 517, 454, 843, 687, 283, 885, 683],
       [779, 237, 820, 386, 243, 453,  23, 409, 345, 901],
       [600, 532, 129, 217, 958, 182, 966, 772, 897, 314],
       [194, 403, 427, 881, 639, 402, 594, 420, 310, 877],
       [555,  83, 117, 531, 348, 763, 369, 786,  59, 223],
       [286, 508, 278, 745, 901, 711, 658,  52, 263, 355],
       [158, 384, 861, 447, 239, 915, 133, 196,  65, 494],
       [ 63,  43, 610, 388, 209, 608, 412, 306, 229, 652],
       [192, 264, 451, 524, 427,  26, 316, 332, 918, 920]])

In [13]:
dict1 = {}
for i in range(root_n):
    dict1[i] = random_matrix[i][m]

dict1

{0: 154, 1: 885, 2: 345, 3: 897, 4: 310, 5: 59, 6: 263, 7: 65, 8: 229, 9: 918}

In [14]:
dict2 = dict(sorted(dict1.items(), key=lambda item: item[1]))
print(dict2)

{5: 59, 7: 65, 0: 154, 8: 229, 6: 263, 4: 310, 2: 345, 1: 885, 3: 897, 9: 918}


In [15]:
np.array(list(dict2.keys()))

array([5, 7, 0, 8, 6, 4, 2, 1, 3, 9])

In [16]:
final_matrix = []
# random_matrix = list(random_matrix)
index_list = np.array(list(dict2.keys()))

for i in range(root_n):
    final_matrix.append( random_matrix[index_list[i]] )

In [17]:
final_matrix

[array([555,  83, 117, 531, 348, 763, 369, 786,  59, 223]),
 array([158, 384, 861, 447, 239, 915, 133, 196,  65, 494]),
 array([466, 847, 320, 602, 608, 490,  78, 363, 154, 778]),
 array([ 63,  43, 610, 388, 209, 608, 412, 306, 229, 652]),
 array([286, 508, 278, 745, 901, 711, 658,  52, 263, 355]),
 array([194, 403, 427, 881, 639, 402, 594, 420, 310, 877]),
 array([779, 237, 820, 386, 243, 453,  23, 409, 345, 901]),
 array([ 94, 371, 113, 517, 454, 843, 687, 283, 885, 683]),
 array([600, 532, 129, 217, 958, 182, 966, 772, 897, 314]),
 array([192, 264, 451, 524, 427,  26, 316, 332, 918, 920])]

In [18]:
m

8

Question 1.g)

In [19]:
m = 7
array = np.ndarray((m, m))

for i in range(m):
    for j in range(m):
        array[i][j] = i+j

In [20]:
array

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 6.,  7.,  8.,  9., 10., 11., 12.]])

###

Question 1.h)

In [21]:
aray = np.ndarray((6, 7, 8))

In [22]:
import sys

element_number = 1
for i in range(6):
    for j in range(7):
        for k in range(8):
            if (element_number == 100):
                print(f'i:{i}, j:{j}, k:{k}')
                sys.exit()
            element_number += 1

i:1, j:5, k:3


SystemExit: 

C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


####

Question 1.i)

In [23]:
import numpy as np
A = np.random.randint(100, size=(5,3))
B = np.random.randint(100, size=(3,2))

In [24]:
A, B

(array([[30, 91, 82],
        [76, 21, 41],
        [42, 30, 80],
        [23, 54, 32],
        [62, 79, 92]]),
 array([[81,  7],
        [ 0, 21],
        [14, 45]]))

In [25]:
np.matmul(A, B)

array([[3578, 5811],
       [6730, 2818],
       [4522, 4524],
       [2311, 2735],
       [6310, 6233]])

####

Question 1.j)

In [26]:
random_vector_again = np.random.randn(10,10)

max_value = float('-inf')

max_value_index_axis0 = 0
max_value_index_axis1 = 0

for i in range(len(random_vector_again[:][0])):
    for j in range(len(random_vector_again[0][:])):
        if random_vector_again[i][j] > random_vector_again[max_value_index_axis0][max_value_index_axis1]:
            max_value = random_vector_again[i][j]
            max_value_index_axis0 = i
            max_value_index_axis1 = j

print(max_value, max_value_index_axis0, max_value_index_axis1)

2.1653240920544317 9 3


In [27]:
random_vector_again[max_value_index_axis0][max_value_index_axis1] = 0

In [28]:
random_vector_again

array([[-0.48439469,  0.74794979,  1.09220649,  0.97545097,  0.13183625,
        -0.96345125,  0.75230045, -1.05255952,  0.17867756, -0.31977055],
       [ 1.84189764, -1.80083627, -0.99249433,  0.79641272, -1.83088303,
        -0.16277901, -0.49069442,  0.30285908, -1.60065637, -0.06949376],
       [ 0.37928518, -0.15740526,  0.31091284, -1.44421503,  0.56219225,
        -0.27835483, -0.44584332, -0.1819823 , -0.23868264,  0.74190112],
       [ 0.3279985 ,  0.19342287,  1.12400764, -0.30885867,  1.75986284,
         0.93205526, -0.3671292 ,  1.33471934,  0.78287382,  0.57143967],
       [ 0.7496605 , -0.5308957 ,  0.42514542,  0.10843884, -0.65082041,
         0.32599158, -0.49808332, -1.70246546,  1.5108306 , -2.02663645],
       [ 1.28890111,  0.92740893,  0.41413549,  0.00975904, -0.51792767,
         0.45805974,  0.2700743 , -1.08132702, -0.65670915, -1.52910804],
       [ 0.40840457,  0.76607633,  0.49282574, -0.59702412, -1.21738208,
         0.97640471,  0.20429974, -1.29110603

####

Question 1.K)

In [30]:
k = 34

array = np.random.randint(100, size=(40))
array

array([23, 72, 44, 49, 18, 43, 59, 67, 71, 32, 17, 88, 80, 32, 13, 23, 54,
        0, 25, 62, 14, 65, 86,  0, 81, 42,  4, 45, 22, 43, 16, 79, 40, 79,
       96, 78, 84,  7, 10, 75])

In [36]:
closest = 0
for i in range(len(array)):
    if abs(array[i] - k) < abs(array[closest] - k):
        closest = i

print(array[closest], closest)

32 9


####

Question 1.l)

In [38]:
final_matrix

[array([555,  83, 117, 531, 348, 763, 369, 786,  59, 223]),
 array([158, 384, 861, 447, 239, 915, 133, 196,  65, 494]),
 array([466, 847, 320, 602, 608, 490,  78, 363, 154, 778]),
 array([ 63,  43, 610, 388, 209, 608, 412, 306, 229, 652]),
 array([286, 508, 278, 745, 901, 711, 658,  52, 263, 355]),
 array([194, 403, 427, 881, 639, 402, 594, 420, 310, 877]),
 array([779, 237, 820, 386, 243, 453,  23, 409, 345, 901]),
 array([ 94, 371, 113, 517, 454, 843, 687, 283, 885, 683]),
 array([600, 532, 129, 217, 958, 182, 966, 772, 897, 314]),
 array([192, 264, 451, 524, 427,  26, 316, 332, 918, 920])]

In [42]:
for i in range(len(final_matrix)):
    mean_of_row = np.mean(final_matrix[i])
    for j in range(len(item)):
        final_matrix[i][j] -= mean_of_row

final_matrix

[array([ 171, -300, -266,  147,  -35,  379,  -14,  402, -324, -160]),
 array([-231,   -5,  471,   57, -150,  525, -256, -193, -324,  104]),
 array([  -4,  376, -150,  131,  137,   19, -392, -107, -316,  307]),
 array([-289, -309,  258,   36, -143,  256,   60,  -46, -123,  300]),
 array([-189,   32, -197,  269,  425,  235,  182, -423, -212, -120]),
 array([-320, -111,  -87,  366,  124, -112,   79,  -94, -204,  362]),
 array([ 319, -222,  360,  -73, -216,   -6, -436,  -50, -114,  441]),
 array([-399, -122, -380,   24,  -39,  350,  194, -210,  392,  190]),
 array([  43,  -24, -427, -339,  401, -374,  409,  215,  340, -242]),
 array([-245, -173,   14,   87,  -10, -411, -121, -105,  481,  483])]

####

#### Question 1.p)

In [45]:
print(np.linalg.matrix_rank(final_matrix))
print(np.linalg.matrix_rank(checker_vector))

10
1


In [46]:
print(np.trace(final_matrix))

542


In [47]:
print(np.linalg.det(final_matrix))

-5.202965676239744e+24


####

#### Question 1.n)

In [51]:
array = np.random.randint(10, size=(90))
array

array([3, 1, 1, 5, 9, 7, 9, 2, 6, 5, 1, 0, 8, 0, 0, 4, 7, 9, 2, 5, 5, 3,
       9, 5, 3, 6, 7, 7, 0, 6, 7, 9, 3, 1, 6, 3, 8, 6, 9, 9, 5, 6, 3, 1,
       1, 6, 4, 0, 6, 0, 8, 5, 8, 6, 2, 2, 7, 8, 9, 1, 0, 2, 4, 9, 8, 7,
       9, 4, 3, 0, 3, 9, 0, 0, 1, 7, 8, 4, 5, 0, 9, 5, 4, 4, 2, 8, 3, 2,
       5, 9])

In [53]:
from scipy import stats

result = stats.mode(array)
result

ModeResult(mode=9, count=13)

####

#### Question 1.o)