In [18]:
import numpy as np

In [22]:
matrix_to_be_built = np.zeros((10,10), dtype=int)
matrix_to_be_built

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
matrix_to_be_built.dtype

dtype('int32')

In [24]:
for i in range(10):
    matrix_to_be_built[i][0] = i+1

for j in range(10):
    matrix_to_be_built[0][j] = j+1

matrix_to_be_built

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 5,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 7,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [10,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [25]:
def build_matrix(i, j):
    if i == 0 or j == 0:
        return matrix_to_be_built[i][j]
    
    matrix_to_be_built[i][j-1] = build_matrix(i, j-1)
    matrix_to_be_built[i-1][j] = build_matrix(i-1, j)
    
    matrix_to_be_built[i][j] = matrix_to_be_built[i][j-1] + matrix_to_be_built[i-1][j]
    return matrix_to_be_built[i][j]

build_matrix(9,9)
matrix_to_be_built

array([[     1,      2,      3,      4,      5,      6,      7,      8,
             9,     10],
       [     2,      4,      7,     11,     16,     22,     29,     37,
            46,     56],
       [     3,      7,     14,     25,     41,     63,     92,    129,
           175,    231],
       [     4,     11,     25,     50,     91,    154,    246,    375,
           550,    781],
       [     5,     16,     41,     91,    182,    336,    582,    957,
          1507,   2288],
       [     6,     22,     63,    154,    336,    672,   1254,   2211,
          3718,   6006],
       [     7,     29,     92,    246,    582,   1254,   2508,   4719,
          8437,  14443],
       [     8,     37,    129,    375,    957,   2211,   4719,   9438,
         17875,  32318],
       [     9,     46,    175,    550,   1507,   3718,   8437,  17875,
         35750,  68068],
       [    10,     56,    231,    781,   2288,   6006,  14443,  32318,
         68068, 136136]])

In [17]:
matrix_to_be_built.dtype

dtype('float64')

In [26]:
print(matrix_to_be_built)

[[     1      2      3      4      5      6      7      8      9     10]
 [     2      4      7     11     16     22     29     37     46     56]
 [     3      7     14     25     41     63     92    129    175    231]
 [     4     11     25     50     91    154    246    375    550    781]
 [     5     16     41     91    182    336    582    957   1507   2288]
 [     6     22     63    154    336    672   1254   2211   3718   6006]
 [     7     29     92    246    582   1254   2508   4719   8437  14443]
 [     8     37    129    375    957   2211   4719   9438  17875  32318]
 [     9     46    175    550   1507   3718   8437  17875  35750  68068]
 [    10     56    231    781   2288   6006  14443  32318  68068 136136]]


In [32]:
bank = []

def snap_matrix(i, j):
    return matrix_to_be_built[i-2:i+1, j-2:j+1]


In [33]:
snap_matrix(2,2)

array([[ 1,  2,  3],
       [ 2,  4,  7],
       [ 3,  7, 14]])

In [39]:
for i in range(10):
    if i < 2:
        continue
    for j in range(10):
        if j < 2:
            continue
        print(i, j)
        bank.append(snap_matrix(i, j))

2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
3 2
3 3
3 4
3 5
3 6
3 7
3 8
3 9
4 2
4 3
4 4
4 5
4 6
4 7
4 8
4 9
5 2
5 3
5 4
5 5
5 6
5 7
5 8
5 9
6 2
6 3
6 4
6 5
6 6
6 7
6 8
6 9
7 2
7 3
7 4
7 5
7 6
7 7
7 8
7 9
8 2
8 3
8 4
8 5
8 6
8 7
8 8
8 9
9 2
9 3
9 4
9 5
9 6
9 7
9 8
9 9


In [37]:
bank

[array([[ 1,  2,  3],
        [ 2,  4,  7],
        [ 3,  7, 14]]),
 array([[ 2,  3,  4],
        [ 4,  7, 11],
        [ 7, 14, 25]]),
 array([[ 3,  4,  5],
        [ 7, 11, 16],
        [14, 25, 41]]),
 array([[ 4,  5,  6],
        [11, 16, 22],
        [25, 41, 63]]),
 array([[ 5,  6,  7],
        [16, 22, 29],
        [41, 63, 92]]),
 array([[  6,   7,   8],
        [ 22,  29,  37],
        [ 63,  92, 129]]),
 array([[  7,   8,   9],
        [ 29,  37,  46],
        [ 92, 129, 175]]),
 array([[  8,   9,  10],
        [ 37,  46,  56],
        [129, 175, 231]]),
 array([[ 2,  4,  7],
        [ 3,  7, 14],
        [ 4, 11, 25]]),
 array([[ 4,  7, 11],
        [ 7, 14, 25],
        [11, 25, 50]]),
 array([[ 7, 11, 16],
        [14, 25, 41],
        [25, 50, 91]]),
 array([[ 11,  16,  22],
        [ 25,  41,  63],
        [ 50,  91, 154]]),
 array([[ 16,  22,  29],
        [ 41,  63,  92],
        [ 91, 154, 246]]),
 array([[ 22,  29,  37],
        [ 63,  92, 129],
        [154, 246, 37

In [38]:
len(bank)

64