In [1]:
import numpy as np

In [7]:
np.version.version

'1.24.3'

In [3]:
a = [1,2,3,4,5]

print(a)
print(a[1])
print(a[1:4])
print(a[-1])
print(type(a))

[1, 2, 3, 4, 5]
2
[2, 3, 4]
5
<class 'list'>


In [4]:
a = np.array([1,2,3,4,5])

print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print(a[1:])

[2 3 4 5]


In [6]:
print(a[:-2])

[1 2 3]


In [7]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5])

In [8]:
print(a)

[ 1  2 10  4  5]


In [20]:
a_mul = np.array([[[1,2,3,1],
                [4,5,6,1],
                [7,8,9,1]],
                
                [[1,1,1,1],
                [2,2,2,2],
                [3,3,3,3]]])
print(a_mul[0])
print("*************")
print(a_mul[0][1])
print("*************")
print(a_mul[0,1])

[[1 2 3 1]
 [4 5 6 1]
 [7 8 9 1]]
*************
[4 5 6 1]
*************
[4 5 6 1]


In [21]:
print(a_mul.shape)

(2, 3, 4)


In [23]:
print(a_mul.ndim)   # dimension

3


In [25]:
print(a_mul.size)   # 2*3*4 = 24

24


In [27]:
# datatype  (numpy is written in C, and it is statically typed and strict)
print(a_mul.dtype)

int32


In [28]:
b = np.array([[[1,2,3,1],
                [4,5,6,1],
                [7,8,9,1]],
                
                [[1, 'hello', 1, 1],
                [2,2,2,2],
                [3,3,3,3]]])
b

array([[['1', '2', '3', '1'],
        ['4', '5', '6', '1'],
        ['7', '8', '9', '1']],

       [['1', 'hello', '1', '1'],
        ['2', '2', '2', '2'],
        ['3', '3', '3', '3']]], dtype='<U11')

In [29]:
print(b.dtype)

<U11


In [33]:
print(int(b[0, 0, 0]))
print(type(b[0, 0, 0]))
print(b[0, 0, 0].dtype)

1
<class 'numpy.str_'>
<U1


In [34]:
c = np.array([[[1,2,3,1],
                [4,5,6,1],
                [7,8,9,1]],
                
                [[1, 'hello', 1, 1],
                [2,2,2,2],
                [3,3,3,3]]], dtype=np.int32)
c

ValueError: invalid literal for int() with base 10: 'hello'

In [35]:
c = np.array([[[1,2,3,1],
                [4,5,6,1],
                [7,8,9,1]],
                
                [[1, '5', 1, 1],
                [2,2,2,2],
                [3,3,3,3]]], dtype=np.int32)
c

array([[[1, 2, 3, 1],
        [4, 5, 6, 1],
        [7, 8, 9, 1]],

       [[1, 5, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]])

In [36]:
d = np.array([[[1,2,3,1],
                [4,5,6,1],
                [7,8,9,1]],
                
                [[1, '5', 1, 1],
                [2,2,2,2],
                [3,3,3,3]]], dtype=np.float32)
d

array([[[1., 2., 3., 1.],
        [4., 5., 6., 1.],
        [7., 8., 9., 1.]],

       [[1., 5., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]]], dtype=float32)

In [38]:
d[1][0][1]

5.0

In [37]:
e = np.array([[[1,2,3,1],
                [4,5,6,1],
                [7,8,9,1]],
                
                [[1, '5', 1, 1],
                [2,2,2,2],
                [3,3,3,3]]])
e

array([[['1', '2', '3', '1'],
        ['4', '5', '6', '1'],
        ['7', '8', '9', '1']],

       [['1', '5', '1', '1'],
        ['2', '2', '2', '2'],
        ['3', '3', '3', '3']]], dtype='<U11')

In [39]:
e[1][0][1]

'5'

In [42]:
dict1 = {'A' : 1}
f = np.array([[[1,2,3,1],
                [4,5,6,1],
                [7,8,9,1]],
                
                [[1, dict, 1, 1],
                [2,2,2,2],
                [3,3,3,3]]])
f

array([[[1, 2, 3, 1],
        [4, 5, 6, 1],
        [7, 8, 9, 1]],

       [[1, <class 'dict'>, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]], dtype=object)

In [44]:
print(f[1][0][0])
print(f[1][0][0].dtype)

1


AttributeError: 'int' object has no attribute 'dtype'

In [45]:
print(type(f[1][0][0]))   # python style object, not C-style

<class 'int'>


In [47]:
g = np.array([[[1,2,3,1],
                [4,5,6,1],
                [7,8,9,1]],
                
                [[1, 2, 1, 1],
                [2,2,2,2],
                [3,3,3,3]]], dtype="<U2")
g

array([[['1', '2', '3', '1'],
        ['4', '5', '6', '1'],
        ['7', '8', '9', '1']],

       [['1', '2', '1', '1'],
        ['2', '2', '2', '2'],
        ['3', '3', '3', '3']]], dtype='<U2')

In [49]:
print(g[0][0][0].dtype)

<U1


In [51]:
a = np.full((2,3,4), 9)
print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [52]:
b = np.full((10,10,10,10), 9)
print(b)

[[[[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  ...

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]]


 [[[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   ...
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]]

  [[9 9 9 ... 9 9 9]
   [9 9 9 ... 9 9 9]
   [

In [53]:
a = np.zeros((10,5,2))
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [54]:
a = np.ones((10,5,2))
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [55]:
a = np.empty((3,3,3))
print(a)

[[[6.23042070e-307 1.42417221e-306 1.60219306e-306]
  [7.56593017e-307 7.56587584e-307 1.37961302e-306]
  [1.05699242e-307 8.01097889e-307 1.78020169e-306]]

 [[7.56601165e-307 1.02359984e-306 8.90092016e-307]
  [1.02361342e-306 6.89804133e-307 8.90104239e-307]
  [8.90098127e-307 8.90111708e-307 6.23054633e-307]]

 [[9.34598926e-307 1.42417629e-306 1.11260687e-306]
  [8.90092016e-307 1.02360867e-306 9.34598925e-307]
  [8.34446411e-308 2.22507386e-306 6.99191991e+247]]]


In [59]:
x_values_1 = np.arange(0, 1000, 5)
print(x_values)

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

In [63]:
x_values_2 = np.linspace(0, 1000, 5)
print(x_values_2)

[   0.  250.  500.  750. 1000.]


In [65]:
x_values_2 = np.linspace(0, 1000, 1001)
print(x_values_2)

[   0.    1.    2. ...  998.  999. 1000.]


In [66]:
print(np.nan)
print(np.inf)

nan
inf


In [67]:
print(np.isnan(np.nan))
print(np.isnan(np.inf))

True
False


In [68]:
print(np.isnan(np.sqrt(-1)))

True


C:\Users\Saswata Mishra\AppData\Local\Temp\ipykernel_24108\1919082837.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))


In [70]:
print(np.sqrt(-1))

nan


C:\Users\Saswata Mishra\AppData\Local\Temp\ipykernel_24108\267541580.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


In [73]:
print(np.isinf( np.array([10]) / 0))

[ True]


C:\Users\Saswata Mishra\AppData\Local\Temp\ipykernel_24108\3665895120.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf( np.array([10]) / 0))


In [74]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]

a1 = np.array(l1)
a2 = np.array(l2)

In [75]:
print(l1 * 5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [76]:
print(a1 * 5)

[ 5 10 15 20 25]


In [77]:
print(l1, a1)

[1, 2, 3, 4, 5] [1 2 3 4 5]


In [79]:
# print(l1 + 5)  # concatination
print(l1 + l2)
print(a1 + 5)
print(a1 + a2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[ 6  7  8  9 10]
[ 7  9 11 13  5]


In [80]:
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)

[-5 -5 -5 -5  5]
[ 6 14 24 36  0]
[0.16666667 0.28571429 0.375      0.44444444        inf]


C:\Users\Saswata Mishra\AppData\Local\Temp\ipykernel_24108\2529889639.py:3: RuntimeWarning: divide by zero encountered in divide
  print(a1 / a2)


In [81]:
a1 = np.array([1,2,3])
a2 = np.array([[1], [2]])

print(a1 + a2)

[[2 3 4]
 [3 4 5]]


In [83]:
print(a1)
print(a2)

[1 2 3]
[[1]
 [2]]


In [84]:
print(a1.T)
print(a2.T)

[1 2 3]
[[1 2]]


In [85]:
print(a1.shape)
print(a2.shape)
print(a1.T.shape)
print(a2.T.shape)

(3,)
(2, 1)
(3,)
(1, 2)


In [2]:
a1 = np.array([[1],[2],[3]])
a2 = np.array([[1],
               [2]])

print(a1 + a2)

ValueError: operands could not be broadcast together with shapes (3,1) (2,1) 

In [3]:
print(a1.shape)
print(a2.shape)

(3, 1)
(2, 1)


In [4]:
a1 = np.array([1, 2, 3])
a2 = np.array([1, 2])

print(a1 + a2)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [5]:
a1.squeeze()

array([1, 2, 3])

In [6]:
np.sqrt(a1)

array([1.        , 1.41421356, 1.73205081])

In [7]:
a1

array([1, 2, 3])

In [8]:
print(a1)

[1 2 3]


In [9]:
np.sin(a1)

array([0.84147098, 0.90929743, 0.14112001])

In [11]:
np.cos(a1)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [12]:
np.arctan(a1)

array([0.78539816, 1.10714872, 1.24904577])

In [14]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [18]:
a = np.array([1, 2, 3])

b = np.append(a, [7, 8, 9])  # usually numpy and pandas functions return the result, they don't change it
print(a, b)

[1 2 3] [1 2 3 7 8 9]


In [19]:
b = np.insert(b, 3, [4,5,6])
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x = np.delete(a, 1)
a

array([1, 2, 3])

In [22]:
x

array([1, 3])

In [24]:
a = np.array([[1,2,3],
             [4,5,6]])

# delete k-th element in row-major where k := np.delete(array, k)
print(np.delete(a, 0))
print(np.delete(a, 1))
print(np.delete(a, 2))
print(np.delete(a, 3))
# print(np.delete)

[2 3 4 5 6]
[1 3 4 5 6]
[1 2 4 5 6]
[1 2 3 5 6]


In [28]:
# big doubt ***************************
print(np.delete(a, axis=0, 0))
print(np.delete(a, 0, 1))

SyntaxError: positional argument follows keyword argument (191334404.py, line 2)

In [38]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a.shape)

(3, 3)


In [39]:
a.ndim

2

In [40]:
print(np.delete(a, 0, 1))

[[2 3]
 [5 6]
 [8 9]]


In [41]:
print(np.delete(a, 1, 0))

[[1 2 3]
 [7 8 9]]


In [42]:
print(np.delete(a, 1, 1))

[[1 3]
 [4 6]
 [7 9]]


In [43]:
print(np.delete(a, 0, 0))

[[4 5 6]
 [7 8 9]]


In [46]:
a = np.arange(1, 21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [47]:
a.shape

(4, 5)

In [50]:
print(a.reshape(5,4) == a.T)
print(a.reshape(5,4))
a

[[ True False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False  True]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [51]:
a.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [52]:
a.reshape(20,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [55]:
a.reshape(20,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [56]:
a.reshape(2, 2, 5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [57]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [58]:
a = a.reshape(5,4)

a.resize(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [61]:
a.resize(5,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [62]:
print(a.flatten())  # flattened copy
print(a.ravel())    # flattened view
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [63]:
var1 = a.flatten()
var1[2] = 100
print(a, var1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] [  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


In [64]:
var1 = a.ravel()
var1[2] = 100
print(a, var1)

[[  1   2 100   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]
 [ 17  18  19  20]] [  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


In [65]:
var = [v for v in a.flat]
print(var)

[1, 2, 100, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [66]:
a

array([[  1,   2, 100,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

In [67]:
a.transpose()

array([[  1,   5,   9,  13,  17],
       [  2,   6,  10,  14,  18],
       [100,   7,  11,  15,  19],
       [  4,   8,  12,  16,  20]])

In [68]:
a

array([[  1,   2, 100,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20]])

In [69]:
a.T

array([[  1,   5,   9,  13,  17],
       [  2,   6,  10,  14,  18],
       [100,   7,  11,  15,  19],
       [  4,   8,  12,  16,  20]])

In [71]:
a.swapaxes(0,1)  # same effect as transposing

array([[  1,   5,   9,  13,  17],
       [  2,   6,  10,  14,  18],
       [100,   7,  11,  15,  19],
       [  4,   8,  12,  16,  20]])

In [73]:
a1 = np.array([[1,2,3,4,5],
               [6,7,8,9,10]])
a2 = np.array([[11,12,13,14,15],
               [16,17,18,19,20]])

a = np.concatenate((a1, a2), axis=0)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [74]:
a = np.concatenate((a1, a2), axis=1)
print(a)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [75]:
a = np.stack((a1, a2), axis=1)
print(a)

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 6  7  8  9 10]
  [16 17 18 19 20]]]


In [77]:
a.shape

(2, 2, 5)

In [81]:
a = np.vstack((a1, a2))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [80]:
a = np.hstack((a1, a2))
print(a)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [82]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [83]:
print(np.split(a, 2, axis=0))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]


In [84]:
print(np.split(a, 4, axis=0))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])]


In [89]:
print(a)
print(np.split(a, 5, axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[array([[ 1],
       [ 6],
       [11],
       [16]]), array([[ 2],
       [ 7],
       [12],
       [17]]), array([[ 3],
       [ 8],
       [13],
       [18]]), array([[ 4],
       [ 9],
       [14],
       [19]]), array([[ 5],
       [10],
       [15],
       [20]])]


### aggregate functions

In [90]:
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())
print(np.median(a))

1
20
10.5
5.766281297335398
210
10.5


In [96]:
numbers = np.random.randn(100)
numbers

array([ 1.33741162e+00,  5.03755689e-02,  1.58835791e-01, -6.42928413e-02,
       -1.03199434e+00, -1.95083514e-01,  1.52107014e+00, -8.99544264e-01,
       -4.95572374e-01,  2.29022138e-01,  1.69604634e+00,  7.47748300e-02,
       -1.11335071e+00,  3.97502630e-01, -1.82159356e+00, -1.37753843e+00,
       -1.98312608e-02, -1.69435655e+00, -2.87954533e-01,  7.71228741e-01,
       -4.21898137e-01,  1.31090906e-01,  2.78318104e-01, -7.78839391e-01,
        1.89282771e-01, -3.86741925e-01, -2.07464681e+00,  3.85437449e-01,
        4.35736515e-01,  5.80631066e-02,  1.80119441e+00, -3.53704247e-01,
       -3.12537253e-01, -9.84708858e-02,  6.55446783e-01, -9.14408698e-01,
       -3.01273903e-01, -1.01057886e+00,  7.08690270e-01, -1.03100121e+00,
        1.37236771e+00,  1.10311442e+00,  6.68901951e-01, -9.72680361e-01,
       -2.12073018e+00, -1.21941642e+00, -5.73510610e-01,  1.13728818e+00,
       -7.37106216e-01, -6.77207040e-01,  4.38736217e-01,  9.34174306e-01,
       -2.11437989e-01,  

In [97]:
numbers = np.random.random(100)
numbers

array([0.04762773, 0.82806865, 0.24473675, 0.18732472, 0.75290802,
       0.16371541, 0.36506886, 0.8721916 , 0.63884103, 0.59655089,
       0.65471586, 0.65459381, 0.56122957, 0.76076476, 0.94995021,
       0.57841657, 0.41819774, 0.06391544, 0.58567484, 0.17616152,
       0.55097818, 0.1601937 , 0.98747331, 0.72849082, 0.80733244,
       0.4762555 , 0.72576113, 0.52557657, 0.90864572, 0.16537484,
       0.24476344, 0.832076  , 0.68814009, 0.67017704, 0.86123272,
       0.75264875, 0.17037242, 0.88187902, 0.48911817, 0.38094849,
       0.91230052, 0.16875553, 0.10212468, 0.67584971, 0.45437302,
       0.3748217 , 0.74795092, 0.53176091, 0.16451794, 0.34521501,
       0.67256707, 0.79756387, 0.94598464, 0.38580197, 0.00103487,
       0.39920425, 0.45695691, 0.21133574, 0.80477411, 0.34231494,
       0.85548407, 0.11525248, 0.38843198, 0.09081503, 0.26787938,
       0.95868247, 0.33593203, 0.82315642, 0.71331276, 0.15294606,
       0.64457393, 0.53082263, 0.10937958, 0.94107126, 0.95520

In [98]:
numbers = np.random.randint(100)
numbers

50

In [99]:
numbers = np.random.randint(90, 100, size=(2,3,4))
numbers

array([[[97, 90, 97, 96],
        [91, 92, 98, 95],
        [95, 98, 93, 95]],

       [[96, 99, 96, 94],
        [93, 93, 94, 93],
        [96, 92, 98, 97]]])

In [104]:
numbers = np.random.binomial(10, p=0.5, size=(5,10))
numbers

array([[7, 7, 4, 5, 3, 7, 5, 3, 2, 6],
       [5, 7, 6, 6, 6, 5, 5, 3, 4, 4],
       [8, 4, 6, 6, 4, 5, 6, 3, 3, 7],
       [7, 6, 3, 3, 7, 7, 8, 2, 6, 7],
       [4, 6, 5, 7, 5, 6, 3, 4, 5, 3]])

In [107]:
numbers = np.random.binomial(10, p=0.1, size=(5,10))
numbers

array([[2, 2, 2, 0, 2, 3, 1, 1, 1, 2],
       [1, 0, 2, 1, 0, 2, 2, 0, 0, 1],
       [0, 3, 0, 1, 0, 2, 2, 1, 0, 1],
       [0, 1, 1, 1, 1, 1, 1, 0, 2, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 1]])

In [108]:
numbers = np.random.normal(loc=170, scale=15, size=(5,10))
numbers

array([[179.83488054, 188.74591303, 164.40782955, 161.90394148,
        172.10197434, 169.51295039, 201.22722564, 163.6909343 ,
        175.55488798, 190.06308592],
       [173.89717205, 173.68930203, 179.67347162, 138.03217135,
        178.8805988 , 170.03001606, 158.98435157, 188.31498598,
        163.4030383 , 165.94852584],
       [165.77136235, 207.16203674, 206.50527754, 174.78744952,
        189.86728506, 159.67009275, 164.35266647, 164.14913532,
        160.83206607, 169.67428259],
       [192.59654345, 180.69828377, 186.86219047, 174.13487497,
        151.84601946, 183.38245788, 164.66581448, 173.8317388 ,
        172.66207869, 188.55593593],
       [139.99475657, 129.57932312, 166.31146905, 174.14700926,
        181.81033808, 153.4633439 , 159.49072785, 153.02795057,
        173.19697028, 167.06296731]])

In [112]:
number = np.random.choice(range(1000), size = (5,10))
number

array([[ 73, 864, 866, 601, 554, 897,  20, 932, 957,   5],
       [  5, 335, 373, 516, 773, 555, 531,  19, 622, 100],
       [635, 160, 941, 214, 548, 255, 103,  74, 563, 974],
       [326,  38, 816, 127,  87, 943, 211, 364, 947, 635],
       [601,  54, 561, 519, 712, 723, 387, 653,  93, 912]])

In [113]:
np.save("./myarray.npy", numbers)

In [114]:
del(numbers)

In [115]:
numbers

NameError: name 'numbers' is not defined

In [116]:
numbers = np.load("./myarray.npy")
numbers

array([[179.83488054, 188.74591303, 164.40782955, 161.90394148,
        172.10197434, 169.51295039, 201.22722564, 163.6909343 ,
        175.55488798, 190.06308592],
       [173.89717205, 173.68930203, 179.67347162, 138.03217135,
        178.8805988 , 170.03001606, 158.98435157, 188.31498598,
        163.4030383 , 165.94852584],
       [165.77136235, 207.16203674, 206.50527754, 174.78744952,
        189.86728506, 159.67009275, 164.35266647, 164.14913532,
        160.83206607, 169.67428259],
       [192.59654345, 180.69828377, 186.86219047, 174.13487497,
        151.84601946, 183.38245788, 164.66581448, 173.8317388 ,
        172.66207869, 188.55593593],
       [139.99475657, 129.57932312, 166.31146905, 174.14700926,
        181.81033808, 153.4633439 , 159.49072785, 153.02795057,
        173.19697028, 167.06296731]])

In [120]:
np.savetxt("./myarray.csv", numbers, delimiter=",")

In [122]:
a = np.loadtxt("./myarray.csv", delimiter=',')
a

array([[179.83488054, 188.74591303, 164.40782955, 161.90394148,
        172.10197434, 169.51295039, 201.22722564, 163.6909343 ,
        175.55488798, 190.06308592],
       [173.89717205, 173.68930203, 179.67347162, 138.03217135,
        178.8805988 , 170.03001606, 158.98435157, 188.31498598,
        163.4030383 , 165.94852584],
       [165.77136235, 207.16203674, 206.50527754, 174.78744952,
        189.86728506, 159.67009275, 164.35266647, 164.14913532,
        160.83206607, 169.67428259],
       [192.59654345, 180.69828377, 186.86219047, 174.13487497,
        151.84601946, 183.38245788, 164.66581448, 173.8317388 ,
        172.66207869, 188.55593593],
       [139.99475657, 129.57932312, 166.31146905, 174.14700926,
        181.81033808, 153.4633439 , 159.49072785, 153.02795057,
        173.19697028, 167.06296731]])

In [124]:
x := []

SyntaxError: invalid syntax (1504294998.py, line 1)