In [52]:
import numpy as np
import copy

In [3]:
a = np.array([1., 2., 3])
a

array([1., 2., 3.])

In [4]:
# size in bytes
a.itemsize

8

In [5]:
a.size

3

In [6]:
a.itemsize * a.size == a.nbytes

True

In [7]:
a = np.array([[1,2,3,4,5,6], [11,12,13,14,15,16]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [8]:
a[0]

array([1, 2, 3, 4, 5, 6])

In [9]:
a[0, :]

array([1, 2, 3, 4, 5, 6])

In [10]:
a[:, 2]

array([ 3, 13])

In [11]:
a[0] == a[0, :]

array([ True,  True,  True,  True,  True,  True])

In [12]:
np.array_equal(a[0], a[0, :])

True

In [13]:
np.allclose(a[0], a[0, :])

True

In [16]:
np.zeros((2,3,3,5,6))

array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0

In [17]:
np.ones((3,1,1), dtype='int32')

array([[[1]],

       [[1]],

       [[1]]], dtype=int32)

In [19]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [20]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [23]:
# random decimal numbers:
np.random.rand(4,2,3)

array([[[0.40775937, 0.1012355 , 0.41367065],
        [0.17299026, 0.0033162 , 0.44154943]],

       [[0.86063669, 0.40010195, 0.27759224],
        [0.60739157, 0.10724194, 0.75092926]],

       [[0.32524556, 0.16715906, 0.25092441],
        [0.75169063, 0.87058379, 0.54232387]],

       [[0.26196201, 0.41025592, 0.45611066],
        [0.41708915, 0.92840329, 0.14422104]]])

In [24]:
np.random.random_sample(a.shape)

array([[0.4161144 , 0.77383489, 0.18386024, 0.81461912, 0.77591094,
        0.58974628],
       [0.05710131, 0.68516114, 0.63237572, 0.77866745, 0.60099087,
        0.15309397]])

In [28]:
np.random.randint(4, 67, size=(3,3))

array([[58, 49, 31],
       [52, 46, 35],
       [48, 33, 10]], dtype=int32)

In [31]:
np.identity(3, dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [38]:
arr = np.array([[1, 2, 3]]*3)
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [41]:
np.repeat(arr, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 1, 1, 2,
       2, 2, 3, 3, 3])

In [45]:
np.repeat([[1, 2, 3]], 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [47]:
op = np.ones((5,5))
print(op)

z = np.zeros((3,3))
print(z)

z[1, 1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [51]:
op[1:-1, 1:-1] = z
print(op)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
k = copy.deepcopy(op)
k [0, 0] = 99
print(k)
print(op)

[[99.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  9.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
m = copy.copy(op)
m[0, 0] = 1000
print(m)
print(op)

[[1000.    1.    1.    1.    1.]
 [   1.    0.    0.    0.    1.]
 [   1.    0.    9.    0.    1.]
 [   1.    0.    0.    0.    1.]
 [   1.    1.    1.    1.    1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Example: Difference between copy.copy and copy.deepcopy
Let's see how shallow and deep copy behave differently with a nested list.

In [55]:
import copy
lst = [[1, 2], [3, 4]]
shallow = copy.copy(lst)
deep = copy.deepcopy(lst)
lst[0][0] = 99
print('Original:', lst)
print('Shallow copy:', shallow)
print('Deep copy:', deep)

Original: [[99, 2], [3, 4]]
Shallow copy: [[99, 2], [3, 4]]
Deep copy: [[1, 2], [3, 4]]


## Linear Algebra

In [56]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [58]:
b = np.full((6,2), 100, dtype='int32')
b

array([[100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100]], dtype=int32)

In [59]:
a.dtype

dtype('int64')

In [61]:
c = np.matmul(a, b)
c

array([[2100, 2100],
       [8100, 8100]])

In [62]:
c.T

array([[2100, 8100],
       [2100, 8100]])

In [63]:
d = np.linalg.det(c)
print(d)

-9.44244682443696e-10


In [64]:
type(d)

numpy.float64

In [65]:
from sympy import Matrix

In [67]:
matrix_sym = Matrix(c)
matrix_sym

Matrix([
[2100, 2100],
[8100, 8100]])

In [68]:
det_of_matrix = matrix_sym.det()
print(det_of_matrix)

0


## Reorganizing arrays

In [71]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8, 1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [73]:
after = before.reshape((2, 2, 2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [74]:
after > 2

array([[[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [75]:
after[after > 2]

array([3, 4, 5, 6, 7, 8])

In [77]:
# you can index with a list in numpy 
x = np.array([1,2,3,4,5,6,7,8,9])
y = [0, 2, -1]
z = np.array(y)
x[y]

array([1, 3, 9])

In [78]:
x[z]

array([1, 3, 9])

In [79]:
grid = np.array([
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30]
])
print(grid)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [99]:
grid[[0, -2, -1]][:, -2:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [101]:
grid[[0, -2, -1], -2:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [102]:
grid[[0, -2, -1], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])